DROP TABLE achat CASCADE CONSTRAINTS;

DROP TABLE appartient_liste CASCADE CONSTRAINTS;

DROP TABLE desir_achat CASCADE CONSTRAINTS;

DROP TABLE liste CASCADE CONSTRAINTS;

DROP TABLE objet CASCADE CONSTRAINTS;

DROP TABLE utilisateur CASCADE CONSTRAINTS;