DROP SEQUENCE idObjet_seq ;

CREATE SEQUENCE idObjet_seq
  START WITH 1
  INCREMENT BY 1
  CACHE 10 ;

DROP SEQUENCE idListe_seq ;

CREATE SEQUENCE idListe_seq
  START WITH 1
  INCREMENT BY 1
  CACHE 10 ;
